// IANA time zones for the airports the sheet knows, so Finavia's UTC timestamps become local clock times.
export const ZONES = {
  HEL:'Europe/Helsinki',OUL:'Europe/Helsinki',RVN:'Europe/Helsinki',KTT:'Europe/Helsinki',IVL:'Europe/Helsinki',KAO:'Europe/Helsinki',KAJ:'Europe/Helsinki',KEM:'Europe/Helsinki',KUO:'Europe/Helsinki',JOE:'Europe/Helsinki',JYV:'Europe/Helsinki',VAA:'Europe/Helsinki',KOK:'Europe/Helsinki',TKU:'Europe/Helsinki',TMP:'Europe/Helsinki',MHQ:'Europe/Mariehamn',POR:'Europe/Helsinki',SVL:'Europe/Helsinki',
  ARN:'Europe/Stockholm',GOT:'Europe/Stockholm',UME:'Europe/Stockholm',VBY:'Europe/Stockholm',OSL:'Europe/Oslo',BGO:'Europe/Oslo',SVG:'Europe/Oslo',TRD:'Europe/Oslo',TOS:'Europe/Oslo',BOO:'Europe/Oslo',ALF:'Europe/Oslo',KKN:'Europe/Oslo',CPH:'Europe/Copenhagen',BLL:'Europe/Copenhagen',KEF:'Atlantic/Reykjavik',
  TLL:'Europe/Tallinn',TAY:'Europe/Tallinn',URE:'Europe/Tallinn',RIX:'Europe/Riga',VNO:'Europe/Vilnius',GDN:'Europe/Warsaw',WAW:'Europe/Warsaw',KRK:'Europe/Warsaw',WMI:'Europe/Warsaw',
  LHR:'Europe/London',LGW:'Europe/London',STN:'Europe/London',MAN:'Europe/London',EDI:'Europe/London',GLA:'Europe/London',ABZ:'Europe/London',NCL:'Europe/London',BHD:'Europe/London',JER:'Europe/Jersey',GIB:'Europe/Gibraltar',DUB:'Europe/Dublin',
  AMS:'Europe/Amsterdam',BRU:'Europe/Brussels',CRL:'Europe/Brussels',LUX:'Europe/Luxembourg',CDG:'Europe/Paris',NCE:'Europe/Paris',GVA:'Europe/Zurich',ZRH:'Europe/Zurich',
  HAM:'Europe/Berlin',BER:'Europe/Berlin',DUS:'Europe/Berlin',FRA:'Europe/Berlin',MUC:'Europe/Berlin',PRG:'Europe/Prague',VIE:'Europe/Vienna',INN:'Europe/Vienna',SZG:'Europe/Vienna',BUD:'Europe/Budapest',LJU:'Europe/Ljubljana',SPU:'Europe/Zagreb',DBV:'Europe/Zagreb',TIV:'Europe/Podgorica',PRN:'Europe/Belgrade',OTP:'Europe/Bucharest',
  MXP:'Europe/Rome',LIN:'Europe/Rome',BGY:'Europe/Rome',TRN:'Europe/Rome',VRN:'Europe/Rome',BLQ:'Europe/Rome',FLR:'Europe/Rome',PSA:'Europe/Rome',VCE:'Europe/Rome',FCO:'Europe/Rome',NAP:'Europe/Rome',CTA:'Europe/Rome',MLA:'Europe/Malta',TIA:'Europe/Tirane',
  ATH:'Europe/Athens',SKG:'Europe/Athens',CFU:'Europe/Athens',PVK:'Europe/Athens',ZTH:'Europe/Athens',CHQ:'Europe/Athens',HER:'Europe/Athens',JTR:'Europe/Athens',KGS:'Europe/Athens',RHO:'Europe/Athens',PFO:'Asia/Nicosia',LCA:'Asia/Nicosia',AYT:'Europe/Istanbul',GZP:'Europe/Istanbul',IST:'Europe/Istanbul',SAW:'Europe/Istanbul',
  OPO:'Europe/Lisbon',LIS:'Europe/Lisbon',FAO:'Europe/Lisbon',FNC:'Atlantic/Madeira',MAD:'Europe/Madrid',BCN:'Europe/Madrid',VLC:'Europe/Madrid',ALC:'Europe/Madrid',PMI:'Europe/Madrid',AGP:'Europe/Madrid',TFS:'Atlantic/Canary',LPA:'Atlantic/Canary',FUE:'Atlantic/Canary',ACE:'Atlantic/Canary',LPI:'Europe/Madrid',
  JFK:'America/New_York',BOS:'America/New_York',IAD:'America/New_York',PHL:'America/New_York',CLT:'America/New_York',RDU:'America/New_York',MCO:'America/New_York',MIA:'America/New_York',ORD:'America/Chicago',DFW:'America/Chicago',MSP:'America/Chicago',STL:'America/Chicago',BNA:'America/Chicago',AUS:'America/Chicago',DTW:'America/Detroit',DEN:'America/Denver',PHX:'America/Phoenix',LAX:'America/Los_Angeles',SFO:'America/Los_Angeles',SAN:'America/Los_Angeles',LAS:'America/Los_Angeles',SEA:'America/Los_Angeles',PDX:'America/Los_Angeles',ANC:'America/Anchorage',HNL:'Pacific/Honolulu',YYZ:'America/Toronto',YYR:'America/Goose_Bay',
  MEX:'America/Mexico_City',CUN:'America/Cancun',SJU:'America/Puerto_Rico',NAS:'America/Nassau',BDA:'Atlantic/Bermuda',BGI:'America/Barbados',GCM:'America/Cayman',BOG:'America/Bogota',MDE:'America/Bogota',UIO:'America/Guayaquil',LIM:'America/Lima',SCL:'America/Santiago',GIG:'America/Sao_Paulo',GRU:'America/Sao_Paulo',MVD:'America/Montevideo',EZE:'America/Argentina/Buenos_Aires',
  DOH:'Asia/Qatar',DXB:'Asia/Dubai',MCT:'Asia/Muscat',RUH:'Asia/Riyadh',JED:'Asia/Riyadh',AMM:'Asia/Amman',CAI:'Africa/Cairo',NBO:'Africa/Nairobi',ZNZ:'Africa/Dar_es_Salaam',JNB:'Africa/Johannesburg',CPT:'Africa/Johannesburg',SEZ:'Indian/Mahe',LOS:'Africa/Lagos',ACC:'Africa/Accra',
  DEL:'Asia/Kolkata',BOM:'Asia/Kolkata',BLR:'Asia/Kolkata',CMB:'Asia/Colombo',MLE:'Indian/Maldives',BKK:'Asia/Bangkok',HKT:'Asia/Bangkok',SGN:'Asia/Ho_Chi_Minh',HAN:'Asia/Ho_Chi_Minh',SIN:'Asia/Singapore',KUL:'Asia/Kuala_Lumpur',PEN:'Asia/Kuala_Lumpur',CGK:'Asia/Jakarta',DPS:'Asia/Makassar',MNL:'Asia/Manila',CEB:'Asia/Manila',HKG:'Asia/Hong_Kong',TPE:'Asia/Taipei',PVG:'Asia/Shanghai',ICN:'Asia/Seoul',HND:'Asia/Tokyo',NRT:'Asia/Tokyo',KIX:'Asia/Tokyo',NGO:'Asia/Tokyo',CTS:'Asia/Tokyo',FUK:'Asia/Tokyo',OKA:'Asia/Tokyo',
  SYD:'Australia/Sydney',CBR:'Australia/Sydney',MEL:'Australia/Melbourne',HBA:'Australia/Hobart',BNE:'Australia/Brisbane',OOL:'Australia/Brisbane',CNS:'Australia/Brisbane',ADL:'Australia/Adelaide',DRW:'Australia/Darwin',PER:'Australia/Perth',AKL:'Pacific/Auckland',CHC:'Pacific/Auckland'
};

// "2026-09-11T02:45:00Z" in the given zone -> "2026-09-11T05:45:00+03:00"
export function toLocal(utcIso, zone) {
  const date = new Date(utcIso);
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-GB', {timeZone: zone, hourCycle: 'h23', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit'}).formatToParts(date).filter(p => p.type !== 'literal').map(p => [p.type, p.value]));
  const local = Date.UTC(+parts.year, +parts.month - 1, +parts.day, +parts.hour, +parts.minute, +parts.second);
  const offset = Math.round((local - date.getTime()) / 60000), sign = offset < 0 ? '-' : '+', abs = Math.abs(offset);
  return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}${sign}${String(Math.floor(abs / 60)).padStart(2, '0')}:${String(abs % 60).padStart(2, '0')}`;
}
